# Generated by Django 4.1 on 2022-08-20 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_account_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
