# Generated by Django 4.1 on 2022-08-22 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageUpload',
        ),
        migrations.RenameField(
            model_name='imageupload',
            old_name='name',
            new_name='title',
        ),
    ]
