# Generated by Django 4.1 on 2022-08-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='contents',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='name',
            field=models.CharField(max_length=255, verbose_name='お名前'),
        ),
    ]
